### ISSUE TITLE
segmentation fault after starting the game

### ISSUE THREAD

**Issue by jose1711** [nickg/lander#4]
```
(gdb) r
Starting program: /usr/bin/lander 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Lunar Lander 0.7

Copyright (C) 2006-2013 Nick Gasson
This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
you are welcome to redistribute it under certain conditions. See the GNU
General Public Licence for details.

[New Thread 0x7ffff264b700 (LWP 20554)]
OpenGL version: 4.6.0 NVIDIA 415.27
[New Thread 0x7fffe1702700 (LWP 20555)]
Found 0 joysticks

Start level 1:
  Dimensions: 2080x1540
  Landing pads: 2
  Asteroids: 7
  Missiles: 0
  Gateways: 0
  Mines: 0

Thread 1 "lander" received signal SIGSEGV, Segmentation fault.
0x00000000400b3d41 in ?? ()
(gdb) bt
#0  0x00000000400b3d41 in ?? ()
#1  0x00007ffff39ef324 in ?? () from /usr/lib/libnvidia-glcore.so.415.27
#2  0x00007ffff39f59d8 in ?? () from /usr/lib/libnvidia-glcore.so.415.27
#3  0x00007ffff358e0ed in ?? () from /usr/lib/libnvidia-glcore.so.415.27
#4  0x000055555556aeeb in Image::Draw (this=this@entry=0x55555634cd80, x=x@entry=768, y=y@entry=568, rotate=0, scale=scale@entry=1, alpha=alpha@entry=1, white=white@entry=1)
    at /home/jose/tarballs/aur4/lander-git/src/lander-git/src/Image.cpp:72
#5  0x000055555556babb in Key::DrawArrow (this=this@entry=0x55555634cd30, viewport=viewport@entry=0x555555b85bb8)
    at /home/jose/tarballs/aur4/lander-git/src/lander-git/src/Key.cpp:80
#6  0x0000555555564784 in Game::Display (this=0x555555b85bb0) at /home/jose/tarballs/aur4/lander-git/src/lander-git/src/Game.cpp:708
#7  0x0000555555573baa in ScreenManager::Display (this=<optimized out>) at /home/jose/tarballs/aur4/lander-git/src/lander-git/src/ScreenManager.cpp:97
#8  0x00005555555705eb in OpenGL::DrawGLScene (this=this@entry=0x5555555b4520 <OpenGL::GetInstance()::opengl>)
    at /home/jose/tarballs/aur4/lander-git/src/lander-git/src/OpenGL.cpp:307
#9  0x00005555555706b1 in OpenGL::Run (this=0x5555555b4520 <OpenGL::GetInstance()::opengl>) at /home/jose/tarballs/aur4/lander-git/src/lander-git/src/OpenGL.cpp:231
#10 0x000055555556d357 in main (argc=<optimized out>, argv=<optimized out>) at /home/jose/tarballs/aur4/lander-git/src/lander-git/src/Main.cpp:155
```
i will provide more information about my system if needed.

**Comment by nickg** [comment]
Sorry for the delay in replying to this. Can you try with the latest master or r0.7.0 tag? I've made a lot of changes to how the game uses OpenGL so this may be fixed now.

**Comment by jose1711** [comment]
confirming that current HEAD no longer gives segfault. thanks for the fix!
